apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-python-hpa
  labels:
    app: demo-python
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-python-deployment  
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
